[versions]
micronaut = "4.0.0-SNAPSHOT"
micronaut-docs = "2.0.0"
micronaut-test = "3.7.0"
micronaut-reactor = "3.0.0-SNAPSHOT"

groovy = "4.0.5"
spotbugs = "4.7.1"

managed-validation = "2.0.1.Final"

[libraries]

#BOMS
micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
groovy-bom = { module = "org.apache.groovy:groovy-bom", version.ref = "groovy" }

groovy-json = { module = "org.apache.groovy:groovy-json" }
spotbugs = { module = "com.github.spotbugs:spotbugs-annotations", version.ref = "spotbugs" }

managed-validation = { module = "javax.validation:validation-api", version.ref = "managed-validation" }
